filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
    filebeat.modules:
    - module: nginx
    - module: postgresql
    - module: system

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
# filebeat.inputs:
#   - type: docker
#     containers.ids: "*"
#     containers.path: /var/lib/docker/containers

output.elasticsearch:
  hosts: 'elasticsearch:9200'
