version: "3.7"
services:
  traefik:
    image: traefik:chevrotin
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      # - ./acme.json:/acme.json
    networks:
      - web

networks:
  web:
    driver: bridge
# https://computerz.solutions/docker-compose-traefik/

# Passer un service derrière Traefik sans HTTPS
#   labels:
#       - traefik.enable=true
#       - traefik.http.routers.NOM-SERVICE.rule=Host(`NOM-SERVICE.NDD`)
#       - traefik.http.routers.NOM-SERVICE.entryPoints=insecure
