apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-service
  labels:
    app: rancher-demo
spec:
  ports:
    - port: 8888
      targetPort: 8080
      name: demo-entry
  selector:
    app: rancher-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo-deployment
  labels:
    app: rancher-demo
spec:
  selector:
    matchLabels:
      app: rancher-demo
  replicas: 5
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - name: rancher-demo-container
        image: monachus/rancher-demo
        ports:
        - containerPort: 8080
          name: demo-entry